### ISSUE TITLE
not showing navi bar

### ISSUE THREAD

**Issue by zizu10** [wp-bootstrap/wp-bootstrap-navwalker#298] opened 2017-08-18 19:17 UTC
Here is my function.php
------------------------------------------------------------------------------------
`<?php
require_once('wp-bootstrap-navwalker.php');
function wpb_theme_setup(){
  register_nav_menus(array(
    'primary' => __('Primary Menu', 'MojaThema'),
  ));
}

add_action('after_setup_theme', 'wpb_theme_setup');`

---------------------------------------------------------------------------------
and I stil dont have menu options in appearance, I only have:
theme
customize
editors
So please help me, what I done wrong?

**Comment by pattonwebz** [comment] 2017-08-19 19:41
Hey zizu10, that link should be there in the Appearance menu even if the theme doesn't register nav menus - so I don't think it's caused by the navwalker. To check you could remove the require and any references to the class from your `wp_nav_menu()` calls.

Do you have any plugins installed on your test site that might affect things? I don't know what to suggest you look at next to help solve the problem :confused:

**Comment by pattonwebz** [comment] 2018-02-01 01:37
This must be caused by a conflict outside of the walker class and with no feedback from OP in a very long time I'm closing this one out for now. If you are still having this problem feel free to reopen the issue and I'll do my best to help out if I can.

**Closed as completed by pattonwebz** 2018-02-01 01:37 UTC
Labels: [STATUS] BEYOND SCOPE OF PROJECT
