### ISSUE TITLE
Dropdown menu is missing the dropdown-toggle class.

### ISSUE THREAD

**Issue by adampatterson** [wp-bootstrap/wp-bootstrap-navwalker#498] opened 2020-12-08 21:47 UTC
#### Steps to reproduce the issue:
A parent menu item that is a page with a few sub-pages.

#### What I expected:
I'd like to see the dropdown toggle.

The dark menu is hardcoded, while the light menu was generated with `WP_Bootstrap_Navwalker`

![image](https://user-images.githubusercontent.com/31537/101528152-27070000-394c-11eb-9426-fe4daae50fd8.png)

#### What happened instead:
The generated HTML functions as a dropdown menu but the parent menu item is missing `dropdown-toggle`.

I followed the code and can see that the `$atts['class'] = 'dropdown-toggle nav-link';` I can also see that the HTML in side of `$item_output` contains the proper classes. 

If I place the dropdown class in the WordPress menu on that item the icon shows under the link.

![image](https://user-images.githubusercontent.com/31537/101544746-73116f00-3963-11eb-8cd8-f8de41e12b82.png)

My Walker code

```
wp_nav_menu(array(
    'menu'           => 'main-menu',
    'theme_location' => 'main-menu',
    'menu_id'        => 'navigation',
    'depth'          => 3,
    'container'      => false,
    'escape_titles'  => false,
    'menu_class'     => 'navbar-nav mr-auto',
    'walker'         => new WP_Bootstrap_Navwalker()
));
```

**Comment by IanDelMar** [comment] 2021-01-25 08:10
I can't reproduce this with the current master branch. Which version of the walker are you using? There was a bug preventing the caret to show up (see #435) which was fixed in #481.

**Comment by adampatterson** [comment] 2021-01-25 14:56
I was logging this at work, but I no longer work there.

But I do still use this package so let me double-check!

**Comment by adampatterson** [comment] 2021-01-26 14:49
@IanDelMar I still don't have the carrots. 

Over the next few days, I will see if I can track it down.

I know that if you follow the execution you do have the proper CSS but at some point, it gets removed.

**Comment by IanDelMar** [comment] 2021-07-22 06:38
@adampatterson Any news on this issue?

**Comment by IanDelMar** [comment] 2021-11-09 05:04
Closing this as the mentioned behavior is still not reproducible. Please re-adress the issue if it comes up again.

**Closed as completed by IanDelMar** 2021-11-09 05:04 UTC

**Comment by adampatterson** [comment] 2021-11-09 07:17
@IanDelMar Hey, Sorry for the long delay.

After much digging, I came across the culprit, there was a filter `nav_menu_css_class` that set the LI links to `nav-item` removing the `data-toggle`!

**Comment by IanDelMar** [comment] 2021-11-09 07:19
@adampatterson Thanks for the feedback!
