### ISSUE TITLE
Including wp-bootstrap-navwalker.php breaks wp-admin

### ISSUE THREAD

**Issue by tiotdev** [wp-bootstrap/wp-bootstrap-navwalker#274] opened 2017-04-15 16:55 UTC
When I include "require_once('wp-bootstrap-navwalker.php');" in my functions.php, some pages of wp-admin (e.g. wp-admin/plugin-install.php?tab=popular) are not longer working (HTTP ERROR 500)

**Comment by curtiplas** [comment] 2017-04-28 14:31
Similar issue where the entire WordPress site breaks sending HTTP Error 500; looks like i have the dependent jquery and css files.  So I'm thinking it might be an incompatibility with our Wordpress Version.

I'm currently running WordPress 4.7.4

**Comment by curtiplas** [comment] 2017-04-28 14:44
is wp-bootstrap-navwalker.php in your root directory of the theme where functions.php lives?

**Comment by lisawedge** [comment] 2017-05-30 12:40
I get the same as tiotdev. I can confirm that the wp-bootstrap-navwalker.php file is certainly in the same folder as functions.php. Any advice?

**Comment by pattonwebz** [comment] 2017-06-14 10:18
Hey Julian,

Could you provide the error log from your server so I could dig into what's causing the 500s? I haven't seen this issue myself before so not sure what the cause is. There will probably be some details in the error log that can help us identify what's up.

**Comment by pattonwebz** [comment] 2017-08-31 19:32
With no response from OP in some time I am going to close this issue for now. Feel free to open it again if this is still a problem.

I expect that the issue here may stem from adding in the walker file in a function that's hooked in on a function which also executes in the admin page (as this should really only be loaded on frontend requests by the theme).

**Comment by gabouh** [comment] 2018-01-15 07:52
Have you double check the name of the file you are including? at the beginning I was having the same issue, I change the name of the file.php and at the require_once('---file---') and It worked.

**Comment by maxine-ellah** [comment] 2018-02-06 03:02
Hey I'm getting the same issue, except I don't get any errors in the console, just a blank page. 
this is what my `functions.php` file looks like:
```
<?php
// Register Custom Navigation Walker
require_once get_template_directory() . '/wp-bootstrap-navwalker.php';

<?php
/* Theme setup */
add_action( 'after_setup_theme', 'wpt_setup' );
    if ( ! function_exists( 'wpt_setup' ) ):
        function wpt_setup() {
            register_nav_menu( 'header-menu', __( 'Header Menu' ) );
        } endif;

        function wpt_register_js() {
            wp_register_script('jquery.bootstrap.min', get_template_directory_uri() . '/js/bootstrap.min.js', 'jquery');
            wp_enqueue_script('jquery.bootstrap.min');
        }
        add_action( 'init', 'wpt_register_js' );
        function wpt_register_css() {
            wp_register_style( 'bootstrap.min', get_template_directory_uri() . '/css/bootstrap.min.css' );
            wp_enqueue_style( 'bootstrap.min' );
        }
        add_action( 'wp_enqueue_scripts', 'wpt_register_css' );
?>

```

New to WP and PHP so any help would be greatly appreciated.

**Comment by pattonwebz** [comment] 2018-02-06 18:40
Hey @maxine-ellah,

I haven't tested the code but quickly looking at it maybe this will fix your whitescreen:

```php
<?php
// Register Custom Navigation Walker
require_once get_template_directory() . '/wp-bootstrap-navwalker.php';

/* Theme setup */
add_action( 'after_setup_theme', 'wpt_setup' );
    if ( ! function_exists( 'wpt_setup' ) ):
        function wpt_setup() {
            register_nav_menu( 'header-menu', __( 'Header Menu' ) );
        } endif;

        function wpt_register_js() {
            wp_register_script('jquery.bootstrap.min', get_template_directory_uri() . '/js/bootstrap.min.js', 'jquery');
            wp_enqueue_script('jquery.bootstrap.min');
        }
        add_action( 'init', 'wpt_register_js' );
        function wpt_register_css() {
            wp_register_style( 'bootstrap.min', get_template_directory_uri() . '/css/bootstrap.min.css' );
            wp_enqueue_style( 'bootstrap.min' );
        }
        add_action( 'wp_enqueue_scripts', 'wpt_register_css' );
```

I removed some opening and closing php tags. `<?php` above theme setup section and `?>` at the end.

**Closed as completed** 2018-02-11 00:45 UTC

**Comment by penguininthefreezer** [comment] 2018-02-26 18:35
I'm having the same problem. White screen of death, error 500.

```
// Register Custom Navigation Walker
require_once get_template_directory() . '/wp_bootstrap_navwalker.php';
```

**Comment by pattonwebz** [comment] 2018-02-26 18:49
@penguininthefreezer The filename was changed quite some time ago and no longer has underscores in it. For the v3-branch walker the filename is `wp-bootstrap-navwalker.php`. For the v4 version (the version in the master branch) the filename is `class-wp-bootstrap-navwalker.php`.

**Comment by penguininthefreezer** [comment] 2018-02-26 18:54
@pattonwebz Is that relevant as long as the filename as well as the call both have underscores?

**Comment by pattonwebz** [comment] 2018-02-26 19:00
LATER EDIT: I understand what your comment was meaning now. And it would not be relevant so long as the call and the filename both match. If that is the case then I am unsure what your problem may be. Are you able to turn on debug mode and see if an error message is thrown to help diagnose the issue?

@penguininthefreezer I'm not sure I understand your latest comment. The mention about name change is relevant because it does not match the example code you provided that requires the filename.

Try to require it with this name if you are using Bootstrap 4:

```
// Register Custom Navigation Walker
require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php';
```

If you are using the version for bootstrap 3 found in the `v3-branch` it will be this:
```
// Register Custom Navigation Walker
require_once get_template_directory() . '/wp-bootstrap-navwalker.php';
```

The readmes in the repos should have instructions about what you should do once you get the file included and past the whitescreen.

**Comment by DeveMan-code** [comment] 2022-05-01 21:29
hello i tried many times to make this code works but i got nothing
the error is: "There has been a critical error on this website.
and this comment: [Learn more about troubleshooting WordPress"
` /**
     * Register Custom Navigation Walker
     */
    function register_navwalker(){
        require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php';
    }
     add_action( 'after_setup_theme', 'register_navwalker' );
    wp_nav_menu( array(
        'theme_location'  => 'primary',
        'depth'           => 2, // 1 = no dropdowns, 2 = with dropdowns.
        'container'       => 'div',
        'container_class' => 'collapse navbar-collapse',
        'container_id'    => 'bs-example-navbar-collapse-1',
        'menu_class'      => 'navbar-nav mr-auto',
        'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
        'walker'          => new WP_Bootstrap_Navwalker(),,
    ) );`
maybe it stopped working in 2022??
note that i took everything from the official site!! 
if someone can answer i will be grateful

**Comment by DeveMan-code** [comment] 2022-05-01 21:30
> /** * Register Custom Navigation Walker */ function register_navwalker(){ require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php'; } add_action( 'after_setup_theme', 'register_navwalker' ); wp_nav_menu( array( 'theme_location' => 'primary', 'depth' => 2, // 1 = no dropdowns, 2 = with dropdowns. 'container' => 'div', 'container_class' => 'collapse navbar-collapse', 'container_id' => 'bs-example-navbar-collapse-1', 'menu_class' => 'navbar-nav mr-auto', 'fallback_cb' => 'WP_Bootstrap_Navwalker::fallback', 'walker' => new WP_Bootstrap_Navwalker(),, ) );
