### ISSUE TITLE
Navwalker not displaying

### ISSUE THREAD

**Issue by Esamattihein** [wp-bootstrap/wp-bootstrap-navwalker#412] opened 2019-02-04 10:18 UTC
Hello,

My Navwalker isn't displaying and I cannot seem to find the reason behind this. I have done several changes and tried to find solutions but cannot find the reason. 

header php:

<!doctype html>
<html <?php language_attributes(); ?>>
  <head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<?php bloginfo('description'); ?>">

    <title>
      <?php bloginfo('name'); ?> | 
      <?php is_front_page() ? bloginfo('description') : wp_title(); ?></title>>
   
    
       <link href="<?php bloginfo('template_url');?>/css/bootstrap.css" rel="stylesheet">

    
    <link href="<?php bloginfo('stylesheet_url'); ?>" rel="stylesheet">
    <?php wp_head(); ?>
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Cover</h3>
          <nav class="nav nav-masthead justify-content-center">NAVBAR 
            <?php
            wp_nav_menu( array(
              'menu' => 'primary',
  'theme_location'  => 'primary',
  'depth'           => 2, // 1 = no dropdowns, 2 = with dropdowns.
  'container'       => 'div',
  'container_class' => 'collapse navbar-collapse',
  'container_id'    => 'bs-example-navbar-collapse-1',
  'menu_class'      => 'nav navbar-nav',
  'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
  'walker'          => new WP_Bootstrap_Navwalker(),
) );
?>
</nav>
        </div>
        
      </header>

functions.php:

<?php
//Register Nav Walker class_alias
require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php';

//Theme Support

function wbp_theme_setup() {
register_nav_menus( array(
'primary' => __('Primary Menu', 'wpbootstrap'),
) );
}

add_action('after_setup_theme' , 'wbp_theme_setup');

Help.

Can somebody understand what I am missing from my code?

**Comment by pattonwebz** [comment] 2019-02-04 15:09
Hey @Esamattihein,

Do you have no menu displaying at all here? This code looks like it should output a menu with the walker or if no menu exists use the walkers fallback - so something should be outputting to the page. If you take a look at the markup of the page does anything at all appear (even something that's there in the markup but not visible in the page) in the place you want the menu to show up?

**Comment by Esamattihein** [comment] 2019-02-05 06:57
Hey @pattonwebz 

Thanks for your reply. This is my first time playing around with PHP so might be confused. I removed my "menu" from header as I wanted to add navwalker so I could through WP easily add new menus. 

Everything was working a while ago but suddenly after adding this I am receiving more and more errors.  Would you be able to help me out ? 

![screenshot 2019-02-04 at 16 01 32](https://user-images.githubusercontent.com/47241089/52257560-f4d98100-2923-11e9-8459-102a112bbc97.png)
<img width="1594" alt="screenshot 2019-01-30 at 15 43 46" src="https://user-images.githubusercontent.com/47241089/52257572-fd31bc00-2923-11e9-92b8-753514dcfa1b.png">

**Comment by pattonwebz** [comment] 2019-02-16 18:58
Hey @Esamattihein,

After looking closer at your code shared in a previous message I see that the markup is missing some closing tags. Check to make sure you are closing the `<nav>` and `<div>` tags. Also the errors suggesting that most of the `=>` are on line number 9 makes me wonder if you have mixed line endings in this file and it's running some of the lines of code together into a single line.

I'm not certain I can help more than this at the moment. If you are able to share with me the generated markup that is created on the pages I might be able to spot something else.

Also the `404` errors about missing map files is usually caused by your build system not copying the maps to the correct locations. It's not a walker issue - it's a style/scripts building issue.

**Comment by pattonwebz** [comment] 2019-03-13 18:54
@Esamattihein any update here? I don't want to close out this issue if you are still facing the problem. I am not certain what more I can do to help at this point though.

**Comment by pattonwebz** [comment] 2019-10-02 18:07
Closing due to how long it's been since this issue received a reply. It can be reopened if this is still an issue.

**Closed as completed by pattonwebz** 2019-10-02 18:07 UTC
