### ISSUE TITLE
Collapse not working

### ISSUE THREAD

**Issue by pedrodev316** [wp-bootstrap/wp-bootstrap-navwalker#281] opened 2017-06-11 15:04 UTC
Hi,

I'm having trouble with the menu as I can't seem to make the collapse work. I'm really not sure where I got the code wrong. Below is the code :

`<div class="blog-masthead">
      <div class="container">
        
        <nav class="blog-nav" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <?php
               wp_nav_menu( array(
                   'menu'              => 'primary',
                   'theme_location'    => 'primary',
                   'depth'             => 2,
                   'container'         => 'div',
                   'container_class'   => 'collapse navbar-collapse',
                   'container_id'      => 'bs-example-navbar-collapse-1',
                   'menu_class'        => 'nav navbar-nav',
                   'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                   'walker'            => new WP_Bootstrap_Navwalker())
               );
              ?>﻿
            </div>
          </div>
        </nav>
        
      </div>
    </div>`

And below is what I defined in my functions.php : 

require_once('WP_Bootstrap_Navwalker.php');

function wpb_theme_setup(){
  // Nav Menus
  register_nav_menus(array(
        'primary' => __( 'Primary Menu' )
      ));
}

Defined my bootstrap.min.js : 

`<script src="<?php bloginfo('template_url'); ?>/js/bootstrap.min.js"></script>`

Any pointers as to where I might have made an error? Thanks in advance!

Best 
```regards,
Peter

**Comment by pattonwebz** [comment] 2017-06-14 09:12
Hey Peter,

On first look your code seems fine to me and I don't immediately see a reason for it not to be working. Bootstrap does need jQuery to be loaded before it's script for it to function so maybe you need to change the order the scripts are added to the page?

If it's an issue with jQuery not being available when it's needed then you will get an error message in the browser console (if your using chrome press `CTRL + SHIFT + J` to open the console). There might be an error there that says something like 'jQuery is undefined' or similar.

Let us know if you see any errors there and if not I'll help dig a bit deeper to find the issue :)

**Comment by smbgood** [comment] 2017-06-15 00:44
I had a similar issue when using this as my menu function:

wp_nav_menu(
	array(
        'menu' => 'primary',
		'theme_location'  => 'primary',
		'container'       => 'div',
		'container_class' => 'collapse navbar-collapse',
		'container_id'    => 'main-navbar-collapse',
		'menu_class'      => 'nav navbar-nav navbar-right',
		'fallback_cb'     => 'wp_page_menu',	
		'depth'           => 2,
		'walker'          => new WP_Bootstrap_Navwalker()
		)
	);

the container div passed to the function wasn't being added so I had to manually add it before my function call (and close it after) and now the collapse is working as intended.

**Comment by pattonwebz** [comment] 2017-07-02 20:44
@smbgood that's interesting that the container items were not outputting to the page and that you had to manually add them to make this work. 

`wp_nav_menu()` should honour container args so I'm wondering if somehow there is a bug somewhere preventing it from working correctly. 

Several issues have been opened over time with this exact problem and seemingly nothing wrong with the code they were using. Reading what you say about container div not outputting I wonder what triggers it to stop outputting and how I can recreate to figure out the solution :confused: 

If you can think of anything non-standard in your WP theme or plugins that might lead to recreating this that would be extremely helpful :)

**Comment by pattonwebz** [comment] 2017-08-31 18:02
I have identified the issue that causes menus to fail when added with similar code to the above. the classes are passed through a function expecting a single class only, since there are multiple in the example call in the readme it fails with this method.

Since there is a resolution here (to manually wrap the container) and that a fix for this is probable in a future version I am closing this for the moment. It can be reopened if future version of the walker does not fix the problem.

**Closed as completed by pattonwebz** 2017-08-31 18:02 UTC

**Comment by llxx-lord-xxll** [comment] 2020-06-25 17:12
@smbgood 
@pattonwebz 


> I had a similar issue when using this as my menu function:
> 
> wp_nav_menu(
> array(
> 'menu' => 'primary',
> 'theme_location' => 'primary',
> 'container' => 'div',
> 'container_class' => 'collapse navbar-collapse',
> 'container_id' => 'main-navbar-collapse',
> 'menu_class' => 'nav navbar-nav navbar-right',
> 'fallback_cb' => 'wp_page_menu',
> 'depth' => 2,
> 'walker' => new WP_Bootstrap_Navwalker()
> )
> );
> 
> the container div passed to the function wasn't being added so I had to manually add it before my function call (and close it after) and now the collapse is working as intended.

Check that if there is anything like this in anywhere, I used "HTML5 Blank" Wordpress Theme boilerplate and i saw this code was disabling container from wp_nav_menu function. Commenting out this thing solved the issue ! 
```
add_filter('wp_nav_menu_args', 'my_wp_nav_menu_args'); // Remove surrounding <div> from WP Navigation
// Remove the <div> surrounding the dynamic navigation to cleanup markup
function my_wp_nav_menu_args($args = '')
{
    $args['container'] = false;
    return $args;
}
```
