### ISSUE TITLE
Replaces entire site with the actual wp_bootstrap_navwalker.php file

### ISSUE THREAD

**Issue by ScarletPonytail** [wp-bootstrap/wp-bootstrap-navwalker#251] opened 2017-03-08 11:51 UTC
I have followed the instructions but clearly I missed something. Perhaps a weird conflict in the functions.php file? With the "require_once" function active in my functions.php, it replaces the entire website with your git page. I have scoured the web and not found anyone else with the same issue, so much be unique to me.

Any advice?

**Comment by brokencase** [comment] 2017-07-10 05:29
I'm experiencing the same thing. Wondering if it's because I'm using underscores?

**Comment by pattonwebz** [comment] 2017-07-10 10:42
I have looked into this a little and haven't been able to recreate it as of yet. I will try with underscores today and see if I can figure it out now I know a theme that it triggers in (I'm not convinced it's the theme that's breaking things, but I don't have a better avenue to explore either :confused:).

**Comment by koki1010** [comment] 2017-09-07 00:58
Fatal error: Uncaught Error: Class 'wp_bootstrap_navwalker' not found in C:\xampp\htdocs\wordpress\wordpress\wp-content\themes\wpbootstrap\header.php:34 Stack trace: #0 C:\xampp\htdocs\wordpress\wordpress\wp-includes\template.php(688): require_once() #1 C:\xampp\htdocs\wordpress\wordpress\wp-includes\template.php(647): load_template('C:\\xampp\\htdocs...', true) #2 C:\xampp\htdocs\wordpress\wordpress\wp-includes\general-template.php(45): locate_template(Array, true) #3 C:\xampp\htdocs\wordpress\wordpress\wp-content\themes\wpbootstrap\index.php(1): get_header() #4 C:\xampp\htdocs\wordpress\wordpress\wp-includes\template-loader.php(74): include('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\wordpress\wordpress\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\wordpress\wordpress\index.php(17): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\wordpress\wordpress\wp-content\themes\wpbootstrap\header.php on line 34

**Comment by pattonwebz** [comment] 2018-01-31 18:52
I have not been able to reproduce this error at all on my end. I am unsure what could be causing the site replacement and I don't even know how that would be possible but obviously there's something that could cause it that I can't quite figure out :s 

@koki1010 it looks like your trying to include the file with the old name (I failed to update all the documentation needed when the name was changed). The new name for the BS3 version is `wp-bootstrap-navwalker.php` and the name for the BS4 version is `class-wp-bootstrap-navwalker.php`.

Since there has been no movement on this ticket for a long time and OP never replied I am closing this out for now but if any of you continue to have this problem reopen this issue or start a fresh one and I'll see if I can get better info to help with figuring it out.

**Closed as completed by pattonwebz** 2018-01-31 18:52 UTC
Labels: [TYPE] IMPLEMENTATION ISSUE
