### ISSUE TITLE
Drop-down top menu link not working

### ISSUE THREAD

**Issue by imalisiddique** [wp-bootstrap/wp-bootstrap-navwalker#209] opened 2015-12-31 07:34 UTC
Drop-down top menu link not working.

**Comment by mindctrl** [comment] 2015-12-31 15:34
We need more info, but usually this is caused by invalid markup or javascript errors. Check your browser dev tools console.

**Comment by jampa** [comment] 2016-01-24 22:54
Happening to me also, when adding a sub navigation menu item, walker strips the url from parent link and makes it "#" instead of keeping the url.

Fix for this here: https://github.com/twittem/wp-bootstrap-navwalker/issues/113

**Comment by alexluecke** [comment] 2016-02-26 01:38
I think it would be reasonable to make this a configurable parameter for the menu.

**Closed as completed** 2016-05-02 10:13 UTC
