### ISSUE TITLE
schema.org support

### ISSUE THREAD

**Issue by bke-daniel** [wp-bootstrap/wp-bootstrap-navwalker#229] opened 2016-07-24 17:22 UTC
Hey there,

woulnd't it be nice to have schema.org support like

``` html
<ul itemscope itemtype="http://www.schema.org/SiteNavigationElement">
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/our-advantage">Our Advantage</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/our-travel-experts">Travel Experts</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/destinations">Destinations</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/cruises">Cruises</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/interests">Interests</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/explore-your-world/interests/hotels-and-resorts">Hotels</a></li>
  <li itemprop="name"><a itemprop="url" href="http://www.travelstore.com/travel-guides">Travel Resources</a></li>
</ul>
```

What do you think?

Have a nice one,
Daniel

**Comment by bhubbard** [comment] 2017-03-14 21:03
Closing as duplicate of #261

**Closed as completed by bhubbard** 2017-03-14 21:03 UTC
