### ISSUE TITLE
does not work for bootstrap 4 (alpha)

### ISSUE THREAD

**Issue by ramonmostert** [wp-bootstrap/wp-bootstrap-navwalker#200] opened 2015-10-27 17:21 UTC
The markup for bootstrap4 navbar has changed (positivily).  Any chance of a bootstrap 4 version coming soon?

**Comment by danimalweb** [comment] 2015-10-30 17:14
Add your support for the BS4 Pull Request here: https://github.com/twittem/wp-bootstrap-navwalker/pull/190

**Comment by bhubbard** [comment] 2017-03-14 22:06
I'm gonna close this issue for now, Bootstrap 4 is in ALPHA, and we do have plans to release an updated version for it.

**Comment by bhubbard** [comment] 2017-03-14 22:07
Duplicate of #238

**Closed as completed by bhubbard** 2017-03-14 22:06 UTC
Labels: [TYPE] DUPLICATE
